# Generated by Django 4.0.1 on 2022-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandcode', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
