# Generated by Django 4.0.1 on 2022-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brandcode', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('imagepath', models.CharField(max_length=100)),
                ('searchword', models.CharField(max_length=100)),
            ],
        ),
    ]
